//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamezone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_engines
    {
        public int game_engine_id { get; set; }
        public Nullable<int> game_id { get; set; }
        public string game_engine_name { get; set; }
        public string game_engine_description { get; set; }
    
        public virtual Game_titles Game_titles { get; set; }
    }
}
