//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamezone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_titles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_titles()
        {
            this.Game_engines = new HashSet<Game_engines>();
            this.Game_stores = new HashSet<Game_stores>();
            this.Streamer_details = new HashSet<Streamer_details>();
            this.Tournament_details = new HashSet<Tournament_details>();
        }
    
        public int game_id { get; set; }
        public string game_name { get; set; }
        public string description { get; set; }
        public string genre { get; set; }
        public string platform { get; set; }
        public string developer { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<double> ign_rate { get; set; }
        public string game_thumbnails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_engines> Game_engines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game_stores> Game_stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Streamer_details> Streamer_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tournament_details> Tournament_details { get; set; }
    }
}
