//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamezone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gaming_organization
    {
        public int org_id { get; set; }
        public string org_name { get; set; }
        public Nullable<System.DateTime> org_establishment_date { get; set; }
        public string org_team_name { get; set; }
        public string org_achievements { get; set; }
    }
}
