//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamezone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesDataEntities2 : DbContext
    {
        public GamesDataEntities2()
            : base("name=GamesDataEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Game_engines> Game_engines { get; set; }
        public virtual DbSet<Game_stores> Game_stores { get; set; }
        public virtual DbSet<Game_titles> Game_titles { get; set; }
        public virtual DbSet<gaming_organization> gaming_organization { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Proplayer> Proplayers { get; set; }
        public virtual DbSet<Streamer_details> Streamer_details { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Tournament_details> Tournament_details { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
