//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamezone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament_details
    {
        public int tournament_id { get; set; }
        public string tournament_name { get; set; }
        public string description { get; set; }
        public Nullable<int> tournament_game_id { get; set; }
        public string tournament_game_name { get; set; }
    
        public virtual Game_titles Game_titles { get; set; }
    }
}
